apiVersion: v1
kind: ConfigMap
metadata:
  name: cliente-app-config
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-svc.oficina-ns.svc.cluster.local:5432/cliente_db"
  SPRING_DATASOURCE_USERNAME: "userClienteDb"
