apiVersion: v1
kind: ConfigMap
metadata:
  name: cliente-app-config
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://academico-rds.cmvwumiyi5g1.us-east-1.rds.amazonaws.com:5432/cliente_db"
  ENV_NAME: "producao"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  POSTGRES_DB: "cliente_db"
