apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  POSTGRES_DB: "cliente_db"
  POSTGRES_USER: "userClienteDb"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cliente-app-config
data:
  SPRING_DATASOURCE_USERNAME: "userClienteDb"
  ENV_NAME: "local"
