apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  POSTGRES_DB: "cliente_db"
  POSTGRES_USER: "userClienteDb"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cliente-app-config
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://academico-rds.cpu6wek2azm8.us-east-1.rds.amazonaws.com:5432/cliente_db"
  SPRING_DATASOURCE_USERNAME: "userClienteDb"
  ENV_NAME: "local"
