apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  POSTGRES_DB: "oficinadb"
  POSTGRES_USER: "userOficinaDb"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cliente-app-config
data:
  SPRING_DATASOURCE_USERNAME: "userOficinaDb"
  ENV_NAME: "local"
