apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - app-configmap.yaml
  - cliente-secret.yaml
  - app-deployment.yaml
  - app-service.yaml
  - app-hpa.yaml

namePrefix: cliente-
namespace: oficina-ns
